In [ ]:
import numpy #pip install numpy command
print(numpy.__version__)

2.3.1


In [ ]:
import numpy as np #import numpy


In [ ]:
#creating array using numpy
x=np.array([1,2,4,56,7,8,9])#create array  
print(x)
print(type(x))#which type of array


[ 1  2  4 56  7  8  9]
<class 'numpy.ndarray'>


In [ ]:
y=np.arange(10)
print(y)#[0 1 2 3 4 5 6 7 8 9]
x=np.arange(-10)
print(x)# it give empty array
z=np.arange(-5,-10,-20)
print(z)#[-5]

[0 1 2 3 4 5 6 7 8 9]
[]
[-5]


In [ ]:
x=np.random.random(size=4) # random array creation using numpy size=4  range(0,1)start to end
print(x)

[0.89816588 0.14377297 0.65241439 0.4037723 ]


In [ ]:
x=np.random.random( size=(3,5)) #create  2d array 3 row and 4 coloum range(0,1)
print(x)

[[0.24702958 0.37040577 0.8819327  0.30704325 0.69328331]
 [0.38434458 0.28913881 0.4087447  0.73997874 0.65077367]
 [0.03618102 0.09660888 0.16110003 0.11453119 0.12625703]]


In [ ]:
x=np.random.randint(50,size=(4,3))# create random 2d array range 0 to 50 -- 4  coloum and 3 row
print(x)

[[20  5 37]
 [16 41 44]
 [41 38  7]
 [ 5 32 49]]


In [14]:
#wap to create three dimensional numpy array with the dimesion 3*3*3 having value in between 15 to 20
x=np.random.randint(low=15,high=20,size=(3,3,3))
print(x)

[[[17 19 15]
  [15 17 17]
  [16 17 15]]

 [[17 19 18]
  [15 17 15]
  [16 16 15]]

 [[16 19 15]
  [15 17 15]
  [16 15 19]]]


In [ ]:
#create[-15 5 25 45 65]array
x=np.arange(-15,66,20)# -15 start 66 end 20 diffrence. 
print(x)

[-15   5  25  45  65]


In [20]:
# convert 1d array to 2d array using reshape
x=np.arange(20)
print(x)
x=np.arange(20).reshape(5,4)#20=5*4....so on 5 row and 4 coloum
print(x)#converted 2d array 4,5
x=np.arange(20).reshape(5,2,2)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]

 [[12 13]
  [14 15]]

 [[16 17]
  [18 19]]]


In [ ]:
#find 2d array values using their index[3,4]row and coloums
arr=np.arange(20).reshape(5,4)
print(arr)#create 2d array
print(arr[0,1]) #1 is value

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
1


In [ ]:
#create 3 d array and find value 
arr=np.arange(20)
arr1=np.arange(20).reshape(2,2,5)
print(arr1)
print(arr1[1,-2,4])#14


[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]]
14
