Q1. Write a program which will be calculate  the mean of each row from a matrix. (Create a matrix of
random elements)



In [ ]:
import numpy as np
rows = 4
cols = 5
matrix = np.random.randint(1, 101, size=(rows, cols))

print("Matrix:")
print(matrix)

row_means = np.mean(matrix, axis=1)






Matrix:
[[75 26 58 87 68]
 [28 77  9 37  5]
 [92 21 88 91 99]
 [39 29 82  1 81]]


Q2. Write a python program to count the number of elements in 2D array.
Test case: Input: np.array([1, 2])
Expected Output: 2

In [ ]:


array=np.arange(10).reshape(5,2)
print(array)
elements=array.size
print(elements)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
10


Q.11 Using a given array make a different array as in below example
array = [1,2,3]
result array -> [1 1 1 2 2 2 3 3 3]
• Internal repeation should be as length of the array.

In [9]:
import numpy as np
array = np.array([1, 2, 3])
n = len(array)
result = np.repeat(array, n)
print("Result array:", result)

Result array: [1 1 1 2 2 2 3 3 3]


Q7. Write a program which makes an array having corresponding max value out of two given
arrays.
Input:
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])
Output: [6 3 1 7 8]


In [13]:
a=np.array([6,3,1,5,8])
b=np.array([3,2,1,7,2])
result=np.maximum(a,b)
print("result",result)

result [6 3 1 7 8]


Q7. Convert negative values in a Series to absolute values:
Test case 1:
Input: Series([-10, 5, -3, 2, -7])
Output: Series([10, 5, 3, 2, 7])

In [ ]:
import pandas as pd
x=pd.Series([-10,5,-3,2,-7])
print(x)
result=pd.Series(x)
print(result)

0   -10
1     5
2    -3
3     2
4    -7
dtype: int64
<bound method NDFrame.__pos__ of 0   -10
1     5
2    -3
3     2
4    -7
dtype: int64>


Q8. Find positions of prime numbers in a Series and return the
count:
Test case 1:
Input: Series([10, 7, 3, 15, 17])
Output: 3

In [ ]:
x=pd.Series([10, 7, 3, 15, 17])


print(x)


AttributeError: module 'pandas' has no attribute 'x'

In [ ]:
import numpy as np

def replace_multiples(arr):
    arr = np.array(arr)  
    arr[(arr % 3 == 0) | (arr % 5 == 0)] = 0
    return arr


input_array = [1, 2, 3, 4, 5, 6, 7, 9]
output_array = replace_multiples(input_array)
print(output_array)


[1 2 0 4 0 0 7 0]
