In [7]:
import numpy as np



BOOLEAN ARRAYS(masks)

In NumPy, a boolean array is an array where each element is either True or False. These are typically used for filtering, masking, or logical operations on arrays.


In [ ]:
#MANUAL CREATION BOOLEAN ARRAYS
import numpy as np

bool_arr = np.array([True, False, True])
print(bool_arr)


[ True False  True]


In [3]:
#COMPARISON IN BOOOLEAN ARRAYS
arr = np.array([1, 2, 3, 4, 5])
bool_arr = arr > 3
print(bool_arr)  # [False False False  True  True]



[False False False  True  True]


SOME TASK PERFORM IN BOOLEAN ARRAYS


In [9]:
a=np.arange(4)
print(a)

[0 1 2 3]


In [10]:
a[[0,-1]]

array([0, 3])

In [14]:
#BOOLEAN ARRAYS
a[[0,1,2,3]]#BOOLEAN ARRAYS

# basic operation
a >= 2 
#compare index value in array[o,1,2,3 >=2]




array([False, False,  True,  True])

In [13]:
a[a >=2]

array([2, 3])