In [3]:
import numpy #pip install numpy command
print(numpy.__version__)

2.3.1


In [1]:
import numpy as np #import numpy


In [ ]:
#creating array using numpy
x=np.array([1,2,4,56,7,8,9])#create array  
print(x)
print(type(x))#which type of array



[ 1  2  4 56  7  8  9]
<class 'numpy.ndarray'>


dtype('int64')

In [ ]:
#if you change data type array
raj=np.array([1,2,3,4])
print(raj)
print(raj.dtype)#int64
raj2=np.array([1,2,3,4],dtype="float")
print(raj2.dtype)#float64

[1 2 3 4]
int64
float64


In [ ]:
y=np.arange(10)
print(y)#[0 1 2 3 4 5 6 7 8 9]
x=np.arange(-10)
print(x)# it give empty array
z=np.arange(-5,-10,-20)
print(z)#[-5]

[0 1 2 3 4 5 6 7 8 9]
[]
[-5]


In [ ]:
x=np.random.random(size=4) # random array creation using numpy size=4  range(0,1)start to end
print(x)

[0.89816588 0.14377297 0.65241439 0.4037723 ]


In [ ]:
x=np.random.random( size=(3,5)) #create  2d array 3 row and 4 coloum range(0,1)
print(x)

[[0.24702958 0.37040577 0.8819327  0.30704325 0.69328331]
 [0.38434458 0.28913881 0.4087447  0.73997874 0.65077367]
 [0.03618102 0.09660888 0.16110003 0.11453119 0.12625703]]


In [ ]:
x=np.random.randint(50,size=(4,3))# create random 2d array range 0 to 50 -- 4  coloum and 3 row
print(x)

[[20  5 37]
 [16 41 44]
 [41 38  7]
 [ 5 32 49]]


In [14]:
#wap to create three dimensional numpy array with the dimesion 3*3*3 having value in between 15 to 20
x=np.random.randint(low=15,high=20,size=(3,3,3))
print(x)

[[[17 19 15]
  [15 17 17]
  [16 17 15]]

 [[17 19 18]
  [15 17 15]
  [16 16 15]]

 [[16 19 15]
  [15 17 15]
  [16 15 19]]]


In [ ]:
#create[-15 5 25 45 65]array
x=np.arange(-15,66,20)# -15 start 66 end 20 diffrence. 
print(x)

[-15   5  25  45  65]


In [20]:
# convert 1d array to 2d array using reshape
x=np.arange(20)
print(x)
x=np.arange(20).reshape(5,4)#20=5*4....so on 5 row and 4 coloum
print(x)#converted 2d array 4,5
x=np.arange(20).reshape(5,2,2)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]

 [[12 13]
  [14 15]]

 [[16 17]
  [18 19]]]


In [ ]:
#find 2d array values using their index[3,4]row and coloums
arr=np.arange(20).reshape(5,4)
print(arr)#create 2d array
print(arr[0,1]) #1 is value

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
1


In [ ]:
#create 3 d array and find value 
arr=np.arange(20)
arr1=np.arange(20).reshape(2,2,5)
print(arr1)
print(arr1[1,-2,4])#14


[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]]
14


slicing operation in 2d array and 3d array

In [ ]:
arr1=np.arange(10)
arr2=np.arange(12).reshape(3,4)
arr3=np.arange(24).reshape(2,4,3)

arr1[3:-1:2]#slicing opeartion {:}-3 starting index -1 endig index 2 

array([3, 5, 7])

In [6]:
#slicing in 1d array (same as python list slicing)
arr1=np.arange(10)
print(arr1[::])
print(arr1[::-1])
print(arr1[2::2])

[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]
[2 4 6 8]


2d array slicing perform

In [7]:
arr2=np.arange(12).reshape(3,4)
arr2[-1::-2,-1::-3]

array([[11,  8],
       [ 3,  0]])

In [9]:
# find [4,6
#8,10] using 2 d array
arr2[1::, ::2]

array([[ 4,  6],
       [ 8, 10]])

In [10]:
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
#slicing in 2d array
print(arr2[0,:])##slicing in 2d array
print(arr2[:,0])
print(arr2[1:,1:])
print(arr2[::,0])




[0 1 2 3]
[0 4 8]
[[ 5  6  7]
 [ 9 10 11]]
[0 4 8]


In [14]:
#slicing perform 3d array
arr3=np.arange(24).reshape(2,4,3)
print(arr3)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [ ]:
#slicing in 3d array
arr3[1,1::2,::2]
print(arr3[0],end='\n\n')
print(arr3[0,0],end='\n\n')
print(arr3[1,:3],end='\n\n')
print(arr3[0,:2,::2])



[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

[0 1 2]

[[12 13 14]
 [15 16 17]
 [18 19 20]]

[[0 2]
 [3 5]]
[[2]
 [5]]


SOME OTHER METHODES IN ND ARRAY

In [ ]:
a1=np.array([1,2,3,4])
a2=np.array([1,2.2,3.3,4.4])
#here "dtypes" specifies the type of element contained in the array
print(a1.dtype)
print(a2.dtype)
#Number of bytes occupies by individual aray elements are available through
print(a1.itemsize)
print(a2.itemsize)
#Number of bytes


SOME OTHER METHODE ABOUT ND ARRAY IN NUMPY


In [ ]:
a1=np.array([1,2,3,4])
a2=np.array([[1,2,3,4],[5,6,7,8]])
#ndim find dimension how many
print(a1.ndim)
print(a2.ndim)

# shape her ek dimesion me kitni value h
print(a1.shape)
print(a2.shape)

#size total size of arry
print(a1.size) 
print(a2.size)

1
2
(4,)
(2, 4)
4
8


NUMPY ARRAY FUNCTION 
{
    ALL VALUE ARE IN ARRAY ZERO /// similar way 1
}

In [28]:
#zero create arrays of 0s
print(np.zeros(10))
print()
print(np.zeros((3,6),dtype="int"))
print()
print(np.zeros((2,3,2)))


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [ ]:
#one create arrays of 1s
print(np.ones(10))
print()
print(np.ones((3,6)))
print()
print(np.ones((2,3,2)))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]

[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


create identity matrix


In [30]:
np.identity(4,dtype="int32")

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]], dtype=int32)

In [31]:
np.identity(3,dtype="int")

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

Arithematic Function with  numpy array

In [5]:
import numpy as np

In [8]:
a1=np.array([1,3,5,7])
a2=np.array([2,4,6,8])

print(a1)
print(a2)

[1 3 5 7]
[2 4 6 8]


Some Arthamatic Operation Performs


In [ ]:
print(a1+a2) 
print(a1*a2) 
print(a1-a2)
print(a1/a2)
print(a1//a2)
print(a1**a2)




[ 3  7 11 15]
[ 2 12 30 56]
[-1 -1 -1 -1]
[0.5        0.75       0.83333333 0.875     ]
[0 0 0 0]
[      1      81   15625 5764801]
